FROM ubuntu:20.04 AS hub-test
RUN apt-get update \
    && DEBIAN_FRONTEND="noninteractive" apt-get install -y gcc make git curl file sudo \
    && curl -sSL https://get.docker.com/ | sh
RUN git clone https://github.com/udhos/update-golang.git \
    && cd update-golang \
    && sudo RELEASE=1.19.4 ./update-golang.sh \
    && ln -s /usr/local/go/bin/go /usr/bin/go
WORKDIR $GOPATH/src/github.com/plgd-dev/hub
COPY go.mod go.sum ./
RUN go mod download
COPY . .

WORKDIR $GOPATH/src/github.com/plgd-dev/hub/tools/cert-tool/cmd
RUN go build -o /usr/bin/cert-tool

WORKDIR $GOPATH/src/github.com/plgd-dev/hub
RUN ( cd /usr/local/go && patch -p1 < $GOPATH/src/github.com/plgd-dev/hub/tools/docker/patches/shrink_tls_conn.patch )
# RUN go mod tidy
# RUN go test ./... || true
