FROM ubuntu:22.04 AS hub-test
RUN apt-get update \
    && DEBIAN_FRONTEND="noninteractive" apt-get install -y --no-install-recommends build-essential ca-certificates curl git make patch sudo \
    && curl -sSL https://get.docker.com/ | sh
# apt: ca-certificates git make sudo
RUN git clone https://github.com/udhos/update-golang.git \
    && cd update-golang \
    && sudo RELEASE=1.20.14 ./update-golang.sh \
    && ln -s /usr/local/go/bin/go /usr/bin/go
WORKDIR $GOPATH/src/github.com/plgd-dev/hub
COPY go.mod go.sum ./
RUN go mod download
COPY . .

WORKDIR $GOPATH/src/github.com/plgd-dev/hub/tools/cert-tool
RUN go build -o /usr/bin/cert-tool

WORKDIR $GOPATH/src/github.com/plgd-dev/hub
# apt: patch
RUN ( cd /usr/local/go && patch -p1 < $GOPATH/src/github.com/plgd-dev/hub/tools/docker/patches/shrink_tls_conn.patch )

# RUN go mod tidy

# apt: build-essential
# RUN go test ./... || true
