// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: grpc-gateway/pb/updateDeviceMetadata.proto

package pb

import (
	events "github.com/plgd-dev/hub/v2/resource-aggregate/events"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateDeviceMetadataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId                 string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	TwinEnabled              bool   `protobuf:"varint,4,opt,name=twin_enabled,json=twinEnabled,proto3" json:"twin_enabled,omitempty"`
	TwinForceSynchronization bool   `protobuf:"varint,5,opt,name=twin_force_synchronization,json=twinForceSynchronization,proto3" json:"twin_force_synchronization,omitempty"` // force synchronization IoT hub with the device resources and set twin_enabled to true. Use to address potential synchronization issues and prevent operational discrepancies.
	TimeToLive               int64  `protobuf:"varint,3,opt,name=time_to_live,json=timeToLive,proto3" json:"time_to_live,omitempty"`                                           // command validity in nanoseconds. 0 means forever and minimal value is 100000000 (100ms).
}

func (x *UpdateDeviceMetadataRequest) Reset() {
	*x = UpdateDeviceMetadataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_gateway_pb_updateDeviceMetadata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDeviceMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceMetadataRequest) ProtoMessage() {}

func (x *UpdateDeviceMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_gateway_pb_updateDeviceMetadata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeviceMetadataRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeviceMetadataRequest) Descriptor() ([]byte, []int) {
	return file_grpc_gateway_pb_updateDeviceMetadata_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateDeviceMetadataRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *UpdateDeviceMetadataRequest) GetTwinEnabled() bool {
	if x != nil {
		return x.TwinEnabled
	}
	return false
}

func (x *UpdateDeviceMetadataRequest) GetTwinForceSynchronization() bool {
	if x != nil {
		return x.TwinForceSynchronization
	}
	return false
}

func (x *UpdateDeviceMetadataRequest) GetTimeToLive() int64 {
	if x != nil {
		return x.TimeToLive
	}
	return 0
}

type UpdateDeviceMetadataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *events.DeviceMetadataUpdated `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdateDeviceMetadataResponse) Reset() {
	*x = UpdateDeviceMetadataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_gateway_pb_updateDeviceMetadata_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDeviceMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceMetadataResponse) ProtoMessage() {}

func (x *UpdateDeviceMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_gateway_pb_updateDeviceMetadata_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeviceMetadataResponse.ProtoReflect.Descriptor instead.
func (*UpdateDeviceMetadataResponse) Descriptor() ([]byte, []int) {
	return file_grpc_gateway_pb_updateDeviceMetadata_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateDeviceMetadataResponse) GetData() *events.DeviceMetadataUpdated {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_grpc_gateway_pb_updateDeviceMetadata_proto protoreflect.FileDescriptor

var file_grpc_gateway_pb_updateDeviceMetadata_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x70,
	0x62, 0x2f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x67, 0x72,
	0x70, 0x63, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x70, 0x62, 0x1a, 0x22, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2d, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65,
	0x2f, 0x70, 0x62, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xc3, 0x01, 0x0a, 0x1b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x21, 0x0a,
	0x0c, 0x74, 0x77, 0x69, 0x6e, 0x5f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0b, 0x74, 0x77, 0x69, 0x6e, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64,
	0x12, 0x3c, 0x0a, 0x1a, 0x74, 0x77, 0x69, 0x6e, 0x5f, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x5f, 0x73,
	0x79, 0x6e, 0x63, 0x68, 0x72, 0x6f, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x18, 0x74, 0x77, 0x69, 0x6e, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x53,
	0x79, 0x6e, 0x63, 0x68, 0x72, 0x6f, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20,
	0x0a, 0x0c, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x74, 0x6f, 0x5f, 0x6c, 0x69, 0x76, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x54, 0x6f, 0x4c, 0x69, 0x76, 0x65,
	0x4a, 0x04, 0x08, 0x02, 0x10, 0x03, 0x22, 0x5f, 0x0a, 0x1c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x61,
	0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6c, 0x67, 0x64, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x68,
	0x75, 0x62, 0x2f, 0x76, 0x32, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x67, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_gateway_pb_updateDeviceMetadata_proto_rawDescOnce sync.Once
	file_grpc_gateway_pb_updateDeviceMetadata_proto_rawDescData = file_grpc_gateway_pb_updateDeviceMetadata_proto_rawDesc
)

func file_grpc_gateway_pb_updateDeviceMetadata_proto_rawDescGZIP() []byte {
	file_grpc_gateway_pb_updateDeviceMetadata_proto_rawDescOnce.Do(func() {
		file_grpc_gateway_pb_updateDeviceMetadata_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_gateway_pb_updateDeviceMetadata_proto_rawDescData)
	})
	return file_grpc_gateway_pb_updateDeviceMetadata_proto_rawDescData
}

var file_grpc_gateway_pb_updateDeviceMetadata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_gateway_pb_updateDeviceMetadata_proto_goTypes = []any{
	(*UpdateDeviceMetadataRequest)(nil),  // 0: grpcgateway.pb.UpdateDeviceMetadataRequest
	(*UpdateDeviceMetadataResponse)(nil), // 1: grpcgateway.pb.UpdateDeviceMetadataResponse
	(*events.DeviceMetadataUpdated)(nil), // 2: resourceaggregate.pb.DeviceMetadataUpdated
}
var file_grpc_gateway_pb_updateDeviceMetadata_proto_depIdxs = []int32{
	2, // 0: grpcgateway.pb.UpdateDeviceMetadataResponse.data:type_name -> resourceaggregate.pb.DeviceMetadataUpdated
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_gateway_pb_updateDeviceMetadata_proto_init() }
func file_grpc_gateway_pb_updateDeviceMetadata_proto_init() {
	if File_grpc_gateway_pb_updateDeviceMetadata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_gateway_pb_updateDeviceMetadata_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateDeviceMetadataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_gateway_pb_updateDeviceMetadata_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateDeviceMetadataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_gateway_pb_updateDeviceMetadata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpc_gateway_pb_updateDeviceMetadata_proto_goTypes,
		DependencyIndexes: file_grpc_gateway_pb_updateDeviceMetadata_proto_depIdxs,
		MessageInfos:      file_grpc_gateway_pb_updateDeviceMetadata_proto_msgTypes,
	}.Build()
	File_grpc_gateway_pb_updateDeviceMetadata_proto = out.File
	file_grpc_gateway_pb_updateDeviceMetadata_proto_rawDesc = nil
	file_grpc_gateway_pb_updateDeviceMetadata_proto_goTypes = nil
	file_grpc_gateway_pb_updateDeviceMetadata_proto_depIdxs = nil
}
