apiVersion: v2
name: plgd-hub
description: A Helm chart for plgd-hub

type: application

# Equals to hub version; set during the release by the pipeline
version: 0.1.0

appVersion: vnext

dependencies:
  - name: "nats"
    version: "1.1.9"
    repository: "https://nats-io.github.io/k8s/helm/charts/"
    condition: nats.enabled
  - name: "mongodb"
    version: "15.6.26"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mongodb.enabled
  - name: "scylla"
    version: "1.10.0"
    repository: "https://scylla-operator-charts.storage.googleapis.com/stable"
    condition: scylla.enabled
