hubID: ""
log:
  level: info
  encoding: json
  stacktrace:
    enabled: false
    level: warn
  encoderConfig:
    timeEncoder: rfc3339nano
apis:
  grpc:
    address: "0.0.0.0:9100"
    sendMsgSize: 4194304
    recvMsgSize: 4194304
    ownerCacheExpiration: 1m
    enforcementPolicy:
      minTime: 5s
      permitWithoutStream: true
    keepAlive:
      # 0s - means infinity
      maxConnectionIdle: 0s
      # 0s - means infinity
      maxConnectionAge: 0s
      # 0s - means infinity
      maxConnectionAgeGrace: 0s
      time: 2h
      timeout: 20s
    tls:
      caPool: "/secrets/public/rootca.crt"
      keyFile: "/secrets/private/cert.key"
      certFile: "/secrets/public/cert.crt"
      clientCertificateRequired: true
    authorization:
      ownerClaim: sub
      audience: ""
      endpoints:
        - authority: ""
          http:
            maxIdleConns: 16
            maxConnsPerHost: 32
            maxIdleConnsPerHost: 16
            idleConnTimeout: "30s"
            timeout: "10s"
            tls:
              caPool: "/secrets/public/rootca.crt"
              keyFile: "/secrets/private/cert.key"
              certFile: "/secrets/public/cert.crt"
              useSystemCAPool: false
      tokenTrustVerification:
        cacheExpiration: 30s
clients:
  eventBus:
    # number of routines to process events in projection
    goPoolSize: 16
    nats:
      url: ""
      pendingLimits:
        msgLimit: 524288
        bytesLimit: 67108864
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
      leadResourceType:
        enabled: false
  eventStore:
    # expiration time of cached resource in projection
    cacheExpiration: 20m
    use: mongoDB
    mongoDB:
      uri: ""
      database: eventStore
      # limits number of connections.
      maxPoolSize: 16
      # close connection when idle time reach the value.
      maxConnIdleTime: 4m0s
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
    cqlDB:
      table: events
      hosts: []
      port: 9142
      numConnections: 16
      connectTimeout: 10s
      useHostnameResolution: true
      reconnectionPolicy:
        constant:
          interval: 3s
          maxRetries: 3
      keyspace:
        name: plgdhub
        create: true
        replication:
          class: SimpleStrategy
          replication_factor: 1
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
  identityStore:
    grpc:
      address: ""
      sendMsgSize: 4194304
      recvMsgSize: 4194304
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
      keepAlive:
        time: 10s
        timeout: 20s
        permitWithoutStream: true
  openTelemetryCollector:
    grpc:
      enabled: false
      address: ""
      sendMsgSize: 4194304
      recvMsgSize: 4194304
      keepAlive:
        time: 10s
        timeout: 20s
        permitWithoutStream: true
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
publicConfiguration:
  caPool: "/secrets/public/rootca.crt"
  authority: ""
  ownerClaim: "sub"
  deviceIDClaim: ""
  coapGateway: ""
  defaultCommandTimeToLive: "0s"
  certificateAuthority: ""
