// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: resource-directory/pb/getLatestDeviceETags.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLatestDeviceETagsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // device id
	Limit    uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                      // limit of the number of etags, 0 means no limit
}

func (x *GetLatestDeviceETagsRequest) Reset() {
	*x = GetLatestDeviceETagsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resource_directory_pb_getLatestDeviceETags_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLatestDeviceETagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestDeviceETagsRequest) ProtoMessage() {}

func (x *GetLatestDeviceETagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_directory_pb_getLatestDeviceETags_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestDeviceETagsRequest.ProtoReflect.Descriptor instead.
func (*GetLatestDeviceETagsRequest) Descriptor() ([]byte, []int) {
	return file_resource_directory_pb_getLatestDeviceETags_proto_rawDescGZIP(), []int{0}
}

func (x *GetLatestDeviceETagsRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetLatestDeviceETagsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetLatestDeviceETagsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Etags [][]byte `protobuf:"bytes,1,rep,name=etags,proto3" json:"etags,omitempty"` // the most recent device etags, each corresponding to a different resource in order of most recent to least recent.
}

func (x *GetLatestDeviceETagsResponse) Reset() {
	*x = GetLatestDeviceETagsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resource_directory_pb_getLatestDeviceETags_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLatestDeviceETagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestDeviceETagsResponse) ProtoMessage() {}

func (x *GetLatestDeviceETagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resource_directory_pb_getLatestDeviceETags_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestDeviceETagsResponse.ProtoReflect.Descriptor instead.
func (*GetLatestDeviceETagsResponse) Descriptor() ([]byte, []int) {
	return file_resource_directory_pb_getLatestDeviceETags_proto_rawDescGZIP(), []int{1}
}

func (x *GetLatestDeviceETagsResponse) GetEtags() [][]byte {
	if x != nil {
		return x.Etags
	}
	return nil
}

var File_resource_directory_pb_getLatestDeviceETags_proto protoreflect.FileDescriptor

var file_resource_directory_pb_getLatestDeviceETags_proto_rawDesc = []byte{
	0x0a, 0x30, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2d, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x79, 0x2f, 0x70, 0x62, 0x2f, 0x67, 0x65, 0x74, 0x4c, 0x61, 0x74, 0x65, 0x73,
	0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x45, 0x54, 0x61, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x14, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x62, 0x22, 0x50, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x4c,
	0x61, 0x74, 0x65, 0x73, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x45, 0x54, 0x61, 0x67, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x34, 0x0a, 0x1c, 0x47, 0x65,
	0x74, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x45, 0x54, 0x61,
	0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x74,
	0x61, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x05, 0x65, 0x74, 0x61, 0x67, 0x73,
	0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70,
	0x6c, 0x67, 0x64, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x68, 0x75, 0x62, 0x2f, 0x76, 0x32, 0x2f, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2d, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x79, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_resource_directory_pb_getLatestDeviceETags_proto_rawDescOnce sync.Once
	file_resource_directory_pb_getLatestDeviceETags_proto_rawDescData = file_resource_directory_pb_getLatestDeviceETags_proto_rawDesc
)

func file_resource_directory_pb_getLatestDeviceETags_proto_rawDescGZIP() []byte {
	file_resource_directory_pb_getLatestDeviceETags_proto_rawDescOnce.Do(func() {
		file_resource_directory_pb_getLatestDeviceETags_proto_rawDescData = protoimpl.X.CompressGZIP(file_resource_directory_pb_getLatestDeviceETags_proto_rawDescData)
	})
	return file_resource_directory_pb_getLatestDeviceETags_proto_rawDescData
}

var file_resource_directory_pb_getLatestDeviceETags_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_resource_directory_pb_getLatestDeviceETags_proto_goTypes = []any{
	(*GetLatestDeviceETagsRequest)(nil),  // 0: resourcedirectory.pb.GetLatestDeviceETagsRequest
	(*GetLatestDeviceETagsResponse)(nil), // 1: resourcedirectory.pb.GetLatestDeviceETagsResponse
}
var file_resource_directory_pb_getLatestDeviceETags_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_resource_directory_pb_getLatestDeviceETags_proto_init() }
func file_resource_directory_pb_getLatestDeviceETags_proto_init() {
	if File_resource_directory_pb_getLatestDeviceETags_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_resource_directory_pb_getLatestDeviceETags_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetLatestDeviceETagsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resource_directory_pb_getLatestDeviceETags_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetLatestDeviceETagsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_resource_directory_pb_getLatestDeviceETags_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resource_directory_pb_getLatestDeviceETags_proto_goTypes,
		DependencyIndexes: file_resource_directory_pb_getLatestDeviceETags_proto_depIdxs,
		MessageInfos:      file_resource_directory_pb_getLatestDeviceETags_proto_msgTypes,
	}.Build()
	File_resource_directory_pb_getLatestDeviceETags_proto = out.File
	file_resource_directory_pb_getLatestDeviceETags_proto_rawDesc = nil
	file_resource_directory_pb_getLatestDeviceETags_proto_goTypes = nil
	file_resource_directory_pb_getLatestDeviceETags_proto_depIdxs = nil
}
