{{- $caSecretData := include "plgd-hub.resolveTemplateString" (list . .Values.global.crl.coap.caPool) }}
{{- $crtSecretData := include "plgd-hub.resolveTemplateString" (list . .Values.global.crl.coap.crt) }}
{{- $keySecretData := include "plgd-hub.resolveTemplateString" (list . .Values.global.crl.coap.key) }}
{{- if (or $caSecretData (and $crtSecretData $keySecretData)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plgd-hub.resolveTemplateString" (list . .Values.crl.coap.secretName) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "plgd-hub.labels" $ | nindent 4 }}
data:
{{- if $caSecretData }}
  {{ include "plgd-hub.resolveTemplateString" (list . .Values.crl.coap.http.tls.caPoolKey) }}: {{ $caSecretData | b64enc }}
{{- end }}
{{- if $crtSecretData }}
  {{ include "plgd-hub.resolveTemplateString" (list . .Values.crl.coap.http.tls.crtKey) }}: {{ $crtSecretData | b64enc }}
{{- end }}
{{- if $keySecretData }}
  {{ include "plgd-hub.resolveTemplateString" (list . .Values.crl.coap.http.tls.keyKey) }}: {{ $keySecretData | b64enc }}
{{- end }}
{{- end }}
