log:
  level: info
  encoding: json
  stacktrace:
    enabled: false
    level: warn
  encoderConfig:
    timeEncoder: rfc3339nano
apis:
  http:
    address: "0.0.0.0:9100"
    readTimeout: 8s
    readHeaderTimeout: 4s
    writeTimeout: 16s
    idleTimeout: 30s
    tls:
      caPool: "/secrets/public/rootca.crt"
      keyFile: "/secrets/private/cert.key"
      certFile: "/secrets/public/cert.crt"
      clientCertificateRequired: true
      crl:
        enabled: false
    webSocket:
      streamBodyLimit: 262144
      pingFrequency: 10s
    authorization:
      audience: ""
      endpoints:
        - authority: ""
          http:
            maxIdleConns: 16
            maxConnsPerHost: 32
            maxIdleConnsPerHost: 16
            idleConnTimeout: "30s"
            timeout: "10s"
            tls:
              caPool: "/secrets/public/rootca.crt"
              keyFile: "/secrets/private/cert.key"
              certFile: "/secrets/public/cert.crt"
              useSystemCAPool: false
              crl:
                enabled: false
      tokenTrustVerification:
        cacheExpiration: 30s
clients:
  grpcGateway:
    grpc:
      address: ""
      sendMsgSize: 4194304
      recvMsgSize: 4194304
      keepAlive:
        time: 10s
        timeout: 20s
        permitWithoutStream: true
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
        crl:
          enabled: false
  openTelemetryCollector:
    grpc:
      enabled: false
      address: ""
      sendMsgSize: 4194304
      recvMsgSize: 4194304
      keepAlive:
        time: 10s
        timeout: 20s
        permitWithoutStream: true
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
        crl:
          enabled: false
ui:
  enabled: false
  directory: "/usr/local/var/www"
  webConfiguration:
    httpGatewayAddress: ""
    deviceProvisioningService: ""
    snippetService: ""
    webOAuthClient:
      authority: ""
      clientID: ""
      audience: ""
      scopes: []
      grantTypes: ["authorization_code"]
    deviceOAuthClient:
      authority: ""
      clientID: ""
      audience: ""
      scopes: []
      providerName: ""
      grantTypes: ["authorization_code"]
    m2mOAuthClient:
      authority: ""
      clientID: ""
      audience: ""
      scopes: []
      providerName: ""
      grantTypes: ["client_credentials"]
      useJWTPrivateKey: true
    visibility:
      mainSidebar:
        certificates: true
        chatRoom: true
        configuration: true
        deviceProvisioning: true
        devices: true
        docs: true
        pendingCommands: true
        remoteClients: true
        dashboard: false
        integrations: false
        deviceFirmwareUpdate: false
        deviceLogs: false
        apiTokens: true
        schemaHub: false
        snippetService: true
