{{- if .Values.identitystore.enabled }}
{{- $identityStoreCertPath := "/certs" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "plgd-hub.identitystore.configName" . }}
  namespace: {{ .Release.Namespace }}
data:
  {{ .Values.identitystore.config.fileName }}: |
    {{- with .Values.identitystore }}
    hubID: {{ required "identitystore.hubId or global.hubId is required" ( .hubId | default $.Values.global.hubId) | quote }}
    log:
      level: {{ .log.level }}
      dumpBody: {{ .log.dumpBody }}
      encoding: {{ .log.encoding }}
      stacktrace:
        enabled: {{ .log.stacktrace.enabled }}
        level: {{ .log.stacktrace.level }}
      encoderConfig:
        timeEncoder: {{ .log.encoderConfig.timeEncoder }}
    apis:
      grpc:
        address: {{  .apis.grpc.address | default (printf "0.0.0.0:%v" .port ) | quote }}
        sendMsgSize: {{ int64 .apis.grpc.sendMsgSize | default 4194304 }}
        recvMsgSize: {{ int64 .apis.grpc.recvMsgSize | default 4194304 }}
        enforcementPolicy:
          minTime: {{ .apis.grpc.enforcementPolicy.minTime | quote }}
          permitWithoutStream: {{ .apis.grpc.enforcementPolicy.permitWithoutStream }}
        keepAlive:
          maxConnectionIdle: {{ .apis.grpc.keepAlive.maxConnectionIdle }}
          maxConnectionAge: {{ .apis.grpc.keepAlive.maxConnectionAge }}
          maxConnectionAgeGrace: {{ .apis.grpc.keepAlive.maxConnectionAgeGrace }}
          time: {{ .apis.grpc.keepAlive.time }}
          timeout: {{ .apis.grpc.keepAlive.timeout }}
        tls:
          {{- $tls := .apis.grpc.tls }}
          {{- include "plgd-hub.internalCertificateConfig" (list $ $tls $identityStoreCertPath ) | indent 8 }}
          clientCertificateRequired: {{ .apis.grpc.tls.clientCertificateRequired }}
          {{- include "plgd-hub.crlInternalConfig" (list $ $tls.crl) | indent 10 }}
        authorization:
          {{- $authorization := .apis.grpc.authorization }}
          {{- include "plgd-hub.authorizationConfig" (list $ $authorization "identitystore.apis.grpc.authorization" $identityStoreCertPath) | indent 8 }}
    clients:
      eventBus:
        nats:
          url: {{ include "plgd-hub.natsUri" (list $ .clients.eventBus.nats.url )  | quote }}
          jetstream: {{ .clients.eventBus.nats.jetstream }}
          flusherTimeout: {{ .clients.eventBus.nats.flusherTimeout | quote }}
          tls:
            {{- $natsTls := .clients.eventBus.nats.tls }}
            {{- include "plgd-hub.internalCertificateConfig" (list $ $natsTls $identityStoreCertPath ) | indent 10 }}
            useSystemCAPool: false
            {{- include "plgd-hub.crlInternalConfig" (list $ $natsTls.crl) | indent 12 }}
      storage:
        use: {{ include "plgd-hub.useDatabase" (list $ . .clients.storage.use)  | quote }}
        mongoDB:
          uri: {{ include "plgd-hub.mongoDBUri" (list $ .clients.storage.mongoDB.uri )  | quote }}
          database: {{ .clients.storage.mongoDB.database }}
          maxPoolSize: {{ .clients.storage.mongoDB.maxPoolSize }}
          maxConnIdleTime: {{ .clients.storage.mongoDB.maxConnIdleTime }}
          tls:
            {{- $mongoDbTls := .clients.storage.mongoDB.tls }}
            {{- include "plgd-hub.internalCertificateConfig" (list $ $mongoDbTls $identityStoreCertPath ) | indent 10 }}
            useSystemCAPool: {{ .clients.storage.mongoDB.tls.useSystemCAPool }}
            {{- include "plgd-hub.crlInternalConfig" (list $ $mongoDbTls.crl) | indent 12 }}
        cqlDB:
          hosts:
          {{- include "plgd-hub.cqlDBHosts" (list $ .clients.storage.cqlDB.hosts ) | indent 8 }}
          port: {{ .clients.storage.cqlDB.port | default 9142 }}
          table: {{ .clients.storage.cqlDB.table | quote }}
          numConnections: {{ .clients.storage.cqlDB.numConnections }}
          connectTimeout: {{ .clients.storage.cqlDB.connectTimeout }}
          useHostnameResolution: {{ .clients.storage.cqlDB.useHostnameResolution }}
          reconnectionPolicy:
            constant:
              interval: {{ .clients.storage.cqlDB.reconnectionPolicy.constant.interval }}
              maxRetries: {{ .clients.storage.cqlDB.reconnectionPolicy.constant.maxRetries }}
          keyspace:
            name: {{ .clients.storage.cqlDB.keyspace.name }}
            create: {{ .clients.storage.cqlDB.keyspace.create }}
            replication:
              {{- toYaml .clients.storage.cqlDB.keyspace.replication | nindent 14 }}
          tls:
            {{- $cqlDbTls := .clients.storage.cqlDB.tls }}
            {{- include "plgd-hub.internalCertificateConfig" (list $ $cqlDbTls $identityStoreCertPath ) | indent 10 }}
            useSystemCAPool: {{ .clients.storage.cqlDB.tls.useSystemCAPool }}
            {{- include "plgd-hub.crlInternalConfig" (list $ $cqlDbTls.crl) | indent 12 }}
      {{- include "plgd-hub.openTelemetryExporterConfig" (list $ $identityStoreCertPath) | nindent 6 }}
  {{- end }}
{{- end }}
