{{- if .Values.identitystore.enabled }}
{{- $cert := "/certs" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plgd-hub.identitystore.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "plgd-hub.labels" . | nindent 4 }}
    {{- with .Values.identitystore.deploymentLabels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  {{- with .Values.identitystore.deploymentAnnotations }}
  annotations:
  {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ include "plgd-hub.replicas" (list $ .Values.identitystore.replicas) }}
  selector:
    matchLabels:
      {{- include "plgd-hub.identitystore.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.identitystore.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "plgd-hub.identitystore.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.identitystore.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.identitystore.rbac.enabled }}
      serviceAccountName: {{ .Values.identitystore.rbac.serviceAccountName }}
      {{- end }}
      {{- with .Values.identitystore.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: {{ .Values.identitystore.restartPolicy }}
      {{- if .Values.identitystore.initContainersTpl }}
      initContainers:
      {{- tpl .Values.identitystore.initContainersTpl . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.identitystore.name }}
          {{- with .Values.identitystore.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "plgd-hub.image" (list . .Values.identitystore) | quote }}
          imagePullPolicy: {{ .Values.identitystore.image.pullPolicy }}
          {{- if .Values.identitystore.command }}
          command:
          {{- range .Values.identitystore.command  }}
            - {{ . | quote }}
          {{- end }}
          {{- end }}
          args:
            - "--config"
            - {{  printf "%s/%s" .Values.identitystore.config.mountPath .Values.identitystore.config.fileName | quote }}
          ports:
            - name: grpc
              containerPort: {{ .Values.identitystore.port }}
              protocol: TCP
          {{- with .Values.identitystore.livenessProbe }}
          livenessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.identitystore.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.identitystore.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: {{ .Values.identitystore.config.volume }}
              mountPath: {{ .Values.identitystore.config.mountPath }}
            {{- if ( include "plgd-hub.identitystore.createServiceCertByCm" . ) }}
            - name: service-crt
              mountPath: {{ $cert }}
            {{- end }}
            {{- include "plgd-hub.extraCAPoolMount" (list . .Values.extraCAPool.authorization) | nindent 12 }}
            {{- include "plgd-hub.extraCAPoolMount" (list . .Values.extraCAPool.internal) | nindent 12 }}
            {{- include "plgd-hub.crlMount" (list . .Values.crl.authorization) | nindent 12 }}
            {{- include "plgd-hub.crlMount" (list . .Values.crl.internal) | nindent 12 }}
            {{- with .Values.identitystore.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- if .Values.identitystore.extraContainers }}
      {{- include "plgd-hub.tplvalues.render" ( dict "value" .Values.identitystore.extraContainers "context" $ ) | nindent 8 }}
      {{- end }}
      volumes:
        {{- if ( include "plgd-hub.identitystore.createServiceCertByCm" . ) }}
        - name: service-crt
          secret:
            secretName: {{ include "plgd-hub.identitystore.serviceCertName" . }}
        {{- end }}
        - name: {{ .Values.identitystore.config.volume }}
          configMap:
            name: {{ include "plgd-hub.identitystore.configName" . }}
        {{- include "plgd-hub.extraCAPoolVolume" (list . .Values.extraCAPool.authorization) | nindent 8 }}
        {{- include "plgd-hub.extraCAPoolVolume" (list . .Values.extraCAPool.internal) | nindent 8 }}
        {{- include "plgd-hub.extraCAPoolVolume" (list . .Values.extraCAPool.storage) | nindent 8 }}
        {{- include "plgd-hub.crlVolume" (list . .Values.crl.authorization) | nindent 8 }}
        {{- include "plgd-hub.crlVolume" (list . .Values.crl.internal) | nindent 8 }}
        {{- include "plgd-hub.crlVolume" (list . .Values.crl.storage) | nindent 8 }}
        {{- with .Values.identitystore.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.identitystore.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.identitystore.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.identitystore.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
