{{- if .Values.resourceaggregate.enabled }}
{{- $resourceAggregateCertPath := "/certs" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "plgd-hub.resourceaggregate.configName" . }}
  namespace: {{ .Release.Namespace }}
data:
  {{ .Values.coapgateway.config.fileName }}: |
    {{- with .Values.resourceaggregate }}
    hubID: {{ required "resourceaggregate.hubId or global.hubId is required" ( .hubId | default $.Values.global.hubId) | quote }}
    log:
      level: {{ .log.level }}
      dumpBody: {{ .log.dumpBody }}
      encoding: {{ .log.encoding }}
      stacktrace:
        enabled: {{ .log.stacktrace.enabled }}
        level: {{ .log.stacktrace.level }}
      encoderConfig:
        timeEncoder: {{ .log.encoderConfig.timeEncoder }}
    apis:
      grpc:
        address: {{ printf "0.0.0.0:%v" .port | quote }}
        sendMsgSize: {{ int64 .apis.grpc.sendMsgSize | default 4194304 }}
        recvMsgSize: {{ int64 .apis.grpc.recvMsgSize | default 4194304 }}
        ownerCacheExpiration: {{ .apis.grpc.ownerCacheExpiration | quote }}
        enforcementPolicy:
          minTime: {{ .apis.grpc.enforcementPolicy.minTime | quote }}
          permitWithoutStream: {{ .apis.grpc.enforcementPolicy.permitWithoutStream }}
        keepAlive:
          maxConnectionIdle: {{ .apis.grpc.keepAlive.maxConnectionIdle }}
          maxConnectionAge: {{ .apis.grpc.keepAlive.maxConnectionAge }}
          maxConnectionAgeGrace: {{ .apis.grpc.keepAlive.maxConnectionAgeGrace }}
          time: {{ .apis.grpc.keepAlive.time }}
          timeout: {{ .apis.grpc.keepAlive.timeout }}
        tls:
          {{- $tls := .apis.grpc.tls }}
          {{- include "plgd-hub.internalCertificateConfig" (list $ $tls $resourceAggregateCertPath) | indent 8 }}
          clientCertificateRequired: {{ .apis.grpc.tls.clientCertificateRequired }}
          {{- include "plgd-hub.crlInternalConfig" (list $ $tls.crl) | indent 10 }}
        authorization:
          {{- $authorization := .apis.grpc.authorization }}
          {{- include "plgd-hub.authorizationConfig" (list $ $authorization "resourceaggregate.apis.grpc.authorization" $resourceAggregateCertPath ) | indent 8 }}
    clients:
      eventBus:
        nats:
          url:{{ printf " " }}{{- include "plgd-hub.natsUri" (list $ .clients.eventBus.nats.url) | quote }}
          flusherTimeout: {{ .clients.eventBus.nats.flusherTimeout | quote }}
          tls:
            {{- $natsTls := .clients.eventBus.nats.tls }}
            {{- include "plgd-hub.internalCertificateConfig" (list $ $natsTls $resourceAggregateCertPath) | indent 10 }}
            useSystemCAPool: {{ .clients.eventBus.nats.tls.useSystemCAPool }}
            {{- include "plgd-hub.crlInternalConfig" (list $ $natsTls.crl) | indent 10 }}
          jetstream: {{ .clients.eventBus.nats.jetstream }}
          {{- $leadResourceType := .clients.eventBus.nats.leadResourceType | default $.Values.global.nats.leadResourceType }}
          {{- if $leadResourceType }}
          leadResourceType:
            enabled: {{ $leadResourceType.enabled | default false }}
            {{- if $leadResourceType.regexFilter }}
            regexFilter: 
            {{- range $leadResourceType.regexFilter }}
              - {{ . | quote }}
            {{- end }}
            {{- end }}
            filter: {{ $leadResourceType.filter | quote }}
            useUUID: {{ $leadResourceType.useUUID | default false }}
          {{- end }}
      eventStore:
        defaultCommandTimeToLive: {{ .clients.eventStore.defaultCommandTimeToLive | default $.Values.global.defaultCommandTimeToLive | quote }}
        occMaxRetry: {{ .clients.eventStore.occMaxRetry }}
        snapshotThreshold: 8
        use: {{ include "plgd-hub.useDatabase" (list $ . .clients.eventStore.use) | quote }}
        mongoDB:
          uri:{{ printf " " }}{{- include "plgd-hub.mongoDBUri" (list $ .clients.eventStore.mongoDB.uri)  | quote }}
          database: {{ .clients.eventStore.mongoDB.database }}
          batchSize: {{ .clients.eventStore.mongoDB.batchSize }}
          maxPoolSize: {{ .clients.eventStore.mongoDB.maxPoolSize }}
          maxConnIdleTime: {{ .clients.eventStore.mongoDB.maxConnIdleTime }}
          tls:
            {{- $mongoTls := .clients.eventStore.mongoDB.tls }}
            {{- include "plgd-hub.internalCertificateConfig" (list $ $mongoTls $resourceAggregateCertPath) | indent 10 }}
            useSystemCAPool: {{ .clients.eventStore.mongoDB.tls.useSystemCAPool }}
            {{- include "plgd-hub.crlInternalConfig" (list $ $mongoTls.crl) | indent 12 }}
        cqlDB:
          hosts:
          {{- include "plgd-hub.cqlDBHosts" (list $ .clients.eventStore.cqlDB.hosts ) | indent 8 }}
          port: {{ .clients.eventStore.cqlDB.port | default 9142 }}
          table: {{ .clients.eventStore.cqlDB.table | quote }}
          numConnections: {{ .clients.eventStore.cqlDB.numConnections }}
          connectTimeout: {{ .clients.eventStore.cqlDB.connectTimeout }}
          useHostnameResolution: {{ .clients.eventStore.cqlDB.useHostnameResolution }}
          reconnectionPolicy:
            constant:
              interval: {{ .clients.eventStore.cqlDB.reconnectionPolicy.constant.interval }}
              maxRetries: {{ .clients.eventStore.cqlDB.reconnectionPolicy.constant.maxRetries }}
          keyspace:
            name: {{ .clients.eventStore.cqlDB.keyspace.name }}
            create: {{ .clients.eventStore.cqlDB.keyspace.create }}
            replication:
              {{- toYaml .clients.eventStore.cqlDB.keyspace.replication | nindent 14 }}
          tls:
            {{- $cqlDbTls := .clients.eventStore.cqlDB.tls }}
            {{- include "plgd-hub.internalCertificateConfig" (list $ $cqlDbTls $resourceAggregateCertPath ) | indent 10 }}
            useSystemCAPool: {{ .clients.eventStore.cqlDB.tls.useSystemCAPool }}
            {{- include "plgd-hub.crlInternalConfig" (list $ $cqlDbTls.crl) | indent 12 }}
      identityStore:
        grpc:
          {{- $authorizationServer := .clients.identityStore.grpc.address }}
          address:{{ printf " " }}{{- include "plgd-hub.identityStoreAddress" (list $ $authorizationServer ) | quote }}
          sendMsgSize: {{ int64 .clients.identityStore.grpc.sendMsgSize | default 4194304 }}
          recvMsgSize: {{ int64 .clients.identityStore.grpc.recvMsgSize | default 4194304 }}
          keepAlive:
            time: {{ .clients.identityStore.grpc.keepAlive.timeout }}
            timeout: {{ .clients.identityStore.grpc.keepAlive.timeout }}
            permitWithoutStream: {{ .clients.identityStore.grpc.keepAlive.permitWithoutStream }}
          tls:
            {{- $authClientTls := .clients.identityStore.grpc.tls }}
            {{- include "plgd-hub.internalCertificateConfig" (list $ $authClientTls $resourceAggregateCertPath) | indent 10 }}
            useSystemCAPool: {{ .clients.identityStore.grpc.tls.useSystemCAPool }}
      {{- include "plgd-hub.openTelemetryExporterConfig" (list $ $resourceAggregateCertPath) | nindent 6 }}
  {{- end }}
{{- end }}
