log:
  level: info
  encoding: json
  stacktrace:
    enabled: false
    level: warn
  encoderConfig:
    timeEncoder: rfc3339nano
apis:
  http:
    address: "0.0.0.0:9100"
    readTimeout: 8s
    readHeaderTimeout: 4s
    writeTimeout: 16s
    idleTimeout: 30s
    tls:
      caPool: "/secrets/public/rootca.crt"
      keyFile: "/secrets/private/cert.key"
      certFile: "/secrets/public/cert.crt"
      clientCertificateRequired: true
      crl:
        enabled: false
    eventsURL: ""
    pullDevices:
      disabled: true
      interval: 5s
    authorization:
      clientID: ""
      clientSecretFile: ""
      scopes: []
      authority: ""
      audience: ""
      ownerClaim: "sub"
      redirectURL: ""
      http:
        maxIdleConns: 16
        maxConnsPerHost: 32
        maxIdleConnsPerHost: 16
        idleConnTimeout: 30s
        timeout: 10s
        tls:
          caPool: "/secrets/public/rootca.crt"
          keyFile: "/secrets/private/cert.key"
          certFile: "/secrets/public/cert.crt"
          useSystemCAPool: false
          crl:
            enabled: false
clients:
  identityStore:
    grpc:
      address: ""
      sendMsgSize: 4194304
      recvMsgSize: 4194304
      keepAlive:
        time: 10s
        timeout: 20s
        permitWithoutStream: true
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
        crl:
          enabled: false
  eventBus:
    nats:
      url: ""
      pendingLimits:
        msgLimit: 524288
        bytesLimit: 67108864
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
        crl:
          enabled: false
      leadResourceType:
        enabled: false
  grpcGateway:
    grpc:
      address: ""
      sendMsgSize: 4194304
      recvMsgSize: 4194304
      keepAlive:
        time: 10s
        timeout: 20s
        permitWithoutStream: true
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
        crl:
          enabled: false
  resourceAggregate:
    grpc:
      address: ""
      sendMsgSize: 4194304
      recvMsgSize: 4194304
      keepAlive:
        time: 10s
        timeout: 20s
        permitWithoutStream: true
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
        crl:
          enabled: false
  storage:
    mongoDB:
      uri: "mongodb://localhost:27017"
      database: "cloud2cloudConnector"
      # limits number of connections.
      maxPoolSize: 16
      # close connection when idle time reach the value.
      maxConnIdleTime: 4m0s
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
        crl:
          enabled: false
  subscription:
    http:
      reconnectInterval: "10s"
      resubscribeInterval: "10s"
  openTelemetryCollector:
    grpc:
      enabled: false
      address: ""
      sendMsgSize: 4194304
      recvMsgSize: 4194304
      keepAlive:
        time: 10s
        timeout: 20s
        permitWithoutStream: true
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
        crl:
          enabled: false
taskProcessor:
  cacheSize: 2048
  timeout: "5s"
  maxParallel: 128
  delay: "0s"
