log:
  dumpBody: false
  level: info
  encoding: json
  stacktrace:
    enabled: false
    level: warn
  encoderConfig:
    timeEncoder: rfc3339nano
apis:
  coap:
    address: "0.0.0.0:5684"
    externalAddress: ""
    protocols:
      - "tcp"
    maxMessageSize: 262144
    ownerCacheExpiration: 1m
    subscriptionBufferSize: 1000
    messagePoolSize: 1000
    requireBatchObserveEnabled: true
    messageQueueSize: 16
    keepAlive:
      timeout: 20s
    blockwiseTransfer:
      enabled: true
      blockSize: "1024"
    tls:
      enabled: true
      disconnectOnExpiredCertificate: false
      caPool: "/secrets/public/rootca.crt"
      keyFile: "/secrets/private/cert.key"
      certFile: "/secrets/public/cert.crt"
      clientCertificateRequired: true
      identityPropertiesRequired: true
      crl:
        enabled: true
        http:
          maxIdleConns: 16
          maxConnsPerHost: 32
          maxIdleConnsPerHost: 16
          idleConnTimeout: "30s"
          timeout: "10s"
          tls:
            caPool: "/secrets/public/rootca.crt"
            keyFile: "/secrets/private/cert.key"
            certFile: "/secrets/public/cert.crt"
            useSystemCAPool: false
            crl:
              enabled: false
    authorization:
      ownerClaim: "sub"
      deviceIDClaim: ""
      audience: ""
      endpoints:
        - authority: ""
          http:
            maxIdleConns: 16
            maxConnsPerHost: 32
            maxIdleConnsPerHost: 16
            idleConnTimeout: "30s"
            timeout: "10s"
            tls:
              caPool: "/secrets/public/rootca.crt"
              keyFile: "/secrets/private/cert.key"
              certFile: "/secrets/public/cert.crt"
              useSystemCAPool: false
              crl:
                enabled: false
      providers:
        - name: "plgd.web"
          clientID: ""
          clientSecretFile: ""
          scopes: []
          audience: ""
          redirectURL: "https://localhost/devices"
          authority: ""
          grantType: ""
          http:
            maxIdleConns: 16
            maxConnsPerHost: 32
            maxIdleConnsPerHost: 16
            idleConnTimeout: 30s
            timeout: 10s
            tls:
              caPool: "/secrets/public/rootca.crt"
              keyFile: "/secrets/private/cert.key"
              certFile: "/secrets/public/cert.crt"
              useSystemCAPool: false
              crl:
                enabled: false
        - name: "plgd.mobile"
          clientID: ""
          clientSecretFile: ""
          scopes: []
          audience: ""
          redirectURL: "cloud.plgd.mobile://login-callback"
          authority: ""
          grantType: ""
          http:
            maxIdleConns: 16
            maxConnsPerHost: 32
            maxIdleConnsPerHost: 16
            idleConnTimeout: 30s
            timeout: 10s
            tls:
              caPool: "/secrets/public/rootca.crt"
              keyFile: "/secrets/private/cert.key"
              certFile: "/secrets/public/cert.crt"
              useSystemCAPool: false
              crl:
                enabled: false
      tokenTrustVerification:
        cacheExpiration: 30s
clients:
  eventBus:
    nats:
      url: ""
      pendingLimits:
        msgLimit: 524288
        bytesLimit: 67108864
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
        crl:
          enabled: false
      leadResourceType:
        enabled: false
  identityStore:
    grpc:
      address: ""
      sendMsgSize: 4194304
      recvMsgSize: 4194304
      keepAlive:
        time: 10s
        timeout: 20s
        permitWithoutStream: true
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
        crl:
          enabled: false
  resourceAggregate:
    grpc:
      address: ""
      sendMsgSize: 4194304
      recvMsgSize: 4194304
      keepAlive:
        time: 10s
        timeout: 20s
        permitWithoutStream: true
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
        crl:
          enabled: false
  resourceDirectory:
    grpc:
      address: ""
      sendMsgSize: 4194304
      recvMsgSize: 4194304
      keepAlive:
        time: 10s
        timeout: 20s
        permitWithoutStream: true
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
        crl:
          enabled: false
  certificateAuthority:
    grpc:
      address: ""
      sendMsgSize: 4194304
      recvMsgSize: 4194304
      keepAlive:
        time: 10s
        timeout: 20s
        permitWithoutStream: true
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
        crl:
          enabled: false
  openTelemetryCollector:
    grpc:
      enabled: false
      address: ""
      sendMsgSize: 4194304
      recvMsgSize: 4194304
      keepAlive:
        time: 10s
        timeout: 20s
        permitWithoutStream: true
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
        crl:
          enabled: false
deviceTwin:
  maxETagsCountInRequest: 8
  useETags: false
taskQueue:
  goPoolSize: 1600
  size: 2097152
  maxIdleTime: "10m"
serviceHeartbeat:
  timeToLive: 1m
