# coap-gateway builded by Golang 1.19.4 has an issue with TLS handshake.
# This issue is reproducible with real devices that connect to AWS.
# This seems to be caused by the device's old mbedtls library:
# https://github.com/Mbed-TLS/mbedtls/tree/d81c11b8ab61fd5b2da8133aa73c5fe33a0633eb
FROM golang:1.21.5-alpine AS build
ARG DIRECTORY
ARG NAME
ARG VERSION
ARG COMMIT_DATE
ARG SHORT_COMMIT
ARG DATE
ARG RELEASE_URL
RUN apk add --no-cache curl git build-base
WORKDIR $GOPATH/src/github.com/plgd-dev/hub
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go mod vendor
RUN ( cd /usr/local/go && patch -p1 < $GOPATH/src/github.com/plgd-dev/hub/tools/docker/patches/shrink_tls_conn.patch )
RUN ( cd ./vendor/golang.org/x/oauth2 && patch -p1 < $GOPATH/src/github.com/plgd-dev/hub/tools/docker/patches/golang_org_x_oauth2_propagate_error.patch )
WORKDIR $GOPATH/src/github.com/plgd-dev/hub/$DIRECTORY
RUN go build -mod=vendor -ldflags "-X github.com/plgd-dev/hub/v2/pkg/build.CommitDate=$COMMIT_DATE -X github.com/plgd-dev/hub/v2/pkg/build.CommitHash=$SHORT_COMMIT -X github.com/plgd-dev/hub/v2/pkg/build.BuildDate=$DATE -X github.com/plgd-dev/hub/v2/pkg/build.Version=$VERSION -X github.com/plgd-dev/hub/v2/pkg/build.ReleaseURL=$RELEASE_URL" -o /go/bin/$NAME ./cmd/service

FROM alpine:3.18 AS service
ARG NAME
RUN apk add --no-cache ca-certificates
COPY --from=build /go/bin/$NAME /usr/local/bin/$NAME
COPY tools/docker/run.sh /usr/local/bin/run.sh
ENV BINARY=$NAME
ENTRYPOINT [ "/usr/local/bin/run.sh" ]