# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create and publish a docker images to github

on:
  workflow_run:
    workflows:
      - "Test"
    branches:
      - main
    types:
      - completed
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      push:
        description: "Push to container registry"
        required: false
        type: boolean
        default: false
env:
  REGISTRY: ghcr.io
  VNEXT_BRANCH: main

jobs:
  build-and-publish-image:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: resource-aggregate
            directory: resource-aggregate
            file: .tmp/docker/resource-aggregate/Dockerfile
            template_file: tools/docker/Dockerfile.in
          - name: resource-directory
            directory: resource-directory
            file: .tmp/docker/resource-directory/Dockerfile
            template_file: tools/docker/Dockerfile.in
          - name: coap-gateway
            directory: coap-gateway
            file: .tmp/docker/coap-gateway/Dockerfile
            template_file: tools/docker/Dockerfile.in
          - name: cloud2cloud-connector
            directory: cloud2cloud-connector
            file: .tmp/docker/cloud2cloud-connector/Dockerfile
            template_file: tools/docker/Dockerfile.in
          - name: cloud2cloud-gateway
            directory: cloud2cloud-gateway
            file: .tmp/docker/cloud2cloud-gateway/Dockerfile
            template_file: tools/docker/Dockerfile.in
          - name: certificate-authority
            directory: certificate-authority
            file: .tmp/docker/certificate-authority/Dockerfile
            template_file: tools/docker/Dockerfile.in
          - name: grpc-gateway
            directory: grpc-gateway
            file: .tmp/docker/grpc-gateway/Dockerfile
            template_file: tools/docker/Dockerfile.in
          - name: http-gateway
            directory: http-gateway
            file: http-gateway/Dockerfile
          - name: identity-store
            directory: identity-store
            file: .tmp/docker/identity-store/Dockerfile
            template_file: tools/docker/Dockerfile.in
          - name: mock-oauth-server
            directory: test/oauth-server
            file: .tmp/docker/mock-oauth-server/Dockerfile
            template_file: tools/docker/Dockerfile.in
          - name: bundle
            directory: bundle
            file: bundle/Dockerfile
          - name: test-cloud-server
            directory: test/cloud-server
            file: test/cloud-server/Dockerfile
          - name: cert-tool
            directory: tools/cert-tool
            file: tools/cert-tool/Dockerfile
    permissions:
      contents: read
      packages: write

    steps:
      - name: CPU Info
        run: |
          cat /proc/cpuinfo
          echo "Number of cores: $(nproc)"
          echo "Number of threads: $(nproc --all)"
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set vars.branch
        id: vars
        run: BRANCH=${GITHUB_REF#refs/*/} && echo ${BRANCH} && echo "branch=${BRANCH}" >> $GITHUB_OUTPUT

      - name: Extract metadata (tags, labels) for docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.name }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=raw,enable=${{ startsWith(steps.vars.outputs.branch, env.VNEXT_BRANCH) }},value=vnext
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,enable=${{ startsWith(steps.vars.outputs.branch, env.VNEXT_BRANCH) }},prefix=vnext-,format=short
      
      - name: Resolve template file
        if: ${{ matrix.template_file }}
        run: |
          mkdir -p $(dirname ${{ matrix.file }})
          awk '{gsub("@NAME@","${{ matrix.name }}")} {gsub("@DIRECTORY@","${{ matrix.directory }}")} {print}' ${{ matrix.template_file }} > ${{ matrix.file }}

      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: ./
          platforms: linux/amd64,linux/arm64
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            DIRECTORY=${{ matrix.directory }}
            NAME=${{ matrix.name }}
          file: ${{ matrix.file }}
          push: ${{ github.event_name != 'workflow_dispatch' || inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
