name: Release Helm Charts
on:
  release:
    types: [published]

jobs:
  release-charts:
    runs-on: ubuntu-24.04
    steps:
      - name: CPU Info
        run: |
          cat /proc/cpuinfo
          echo "Number of cores: $(nproc)"
          echo "Number of threads: $(nproc --all)"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_url: https://charts.plgd.dev
          helm_version: "3.7.1"
          app_version: "${{ steps.get_version.outputs.VERSION }}"
          chart_version: "${{ steps.get_version.outputs.VERSION }}"
